name: Build pull request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build
        run: xmake
