name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build
        run: xmake -y

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build distribution packages
        if: steps.release.outputs.new_release_published == 'true'
        run: xmake build_dist

      - name: Upload artifacts
        if: steps.release.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.release.outputs.new_release_git_tag }}
          files: dist/*.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
